### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by NathNathNathNath** [proglottis/ladder#53]

**Comment by proglottis** [comment]
It shouldn't be too hard to add a period to Tournament. It's only the job that makes it a week.
https://github.com/proglottis/ladder/blob/master/config/schedule.rb#L4

A week was chosen pretty arbitrarily because the Glicko paper suggests quite a lot of games per person per rating period:
> The Glicko-2 system works best when the number of games in a rating period is moderate to large, say an average of at least 10-15 games per player in a rating period

And a week is probably as long as I would want to wait while trying to keep things interesting.
